In [1]:
#import the required modules
import numpy as np
import pandas as pd


In [2]:
first we need to understand what a set is cause its essentioal to 
linearalgebra.
In mathematics set is a colection fo objects and denoted by braces{}
s={orange,apple,banana}
This means that s is a set of orange apple and bananas
Empty sets are denoted by {} or ∅ .
given two set A and B we are able to show that :
    A∪B union of A and B equal to set of containin all elements of A and B
    
    
    

SyntaxError: invalid syntax (2483634025.py, line 1)

In [6]:
#uses the zeros and ones function form the numpy modules to create an n-dimesional array of ones and
#zeros as seen in the output
zero=np.zeros((3,3))
print(zero)
one=np.ones((2,2))
print(one)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
#create a row and column vector using the array funtion form the numpy modulw

vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],[2],[3],[4]])
print(vector_row.shape)
print(vector_row)
print(vector_column.shape)
print(vector_column)

In [11]:
#the code below is for calculateing the norml of a vector using the linalg module
# it takes two argument the object eg the vector and the method use to  find the normal usually in two 
#figues 1(the Manhattan distance) and 2(Euclidean distance) also the p-norm which is towards infinity 
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


In [3]:
#angles between two vectors buy dusing the dot and cross product and
#getting the cos inverse.
from numpy import arccos, dot
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

NameError: name 'norm' is not defined

In [14]:
#cross product 
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


In [4]:
#here x is represented as a linear combination of v w and u which results in a new vector 
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [5]:
#matrices
P=np.array([[1,7],[2,3],[5,0]])
Q=np.array([[2,6,3,1],[1,2,3,4]])
print(P)
print(Q)
print(np.dot(P,Q))


[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [16]:
#square matrices are important in calculating the 
#determinat and inverse the determinant if found in the numpy.linalg module
#the inverse is a poduct of the dot product of the matrics and the identity of the matrics
from numpy.linalg import det
M=np.array([[0,2,1,3],[3,2,8,1],[1,0,0,3],[0,3,2,1]])
print("M:\n",M)
print("Determinant : %.lf",det(M))
I=np.eye(4)
print("I:\n",I)
print("M*I:\n",np.dot(M,I))


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant : %.lf -38.000000000000014
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [12]:
#use the inv module form the linalg pacK
from numpy.linalg import inv
print("Inv M:\n",inv(M))
P=np.array([[0,1,1],[0,0,0],[1,0,1]])
print(P)
print("det(P):\n",det(P))


Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
[[0 1 1]
 [0 0 0]
 [1 0 1]]
det(P):
 0.0


In [14]:
#calculation of the condition number (cond function )and rank (matrix_rank function)
#the rank of a matrix is the number of independet rows and columns in a matrics
#full rank if the rank of rows and columns are equal 
from numpy.linalg import cond, matrix_rank
A = np.array([[1,1,0],
[0,1,0],
[1,0,1]])
print(A)
print("Condition number:\n", cond(A))
print("Rank:\n", matrix_rank(A))
y = np.array([[1], [2], [1]])
print(y)
A_y = np.concatenate((A, y), axis = 1)
print("Augmented matrix:\n", A_y)

[[1 1 0]
 [0 1 0]
 [1 0 1]]
Condition number:
 4.048917339522305
Rank:
 3
[[1]
 [2]
 [1]]
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [17]:
"""Matrix A=[[1,1,0],[0,1,0],[1,0,1]], compute the condition number and rank for this matrix. If y=[[1],[2],[1]], get the augmented matrix [A, y].
A matrics with out an inverse is called a singular matrix and one 
with a determinant is a non-singular matrix.
A matrix with a determinat that tends towards zero is called an ill conditioned matrix
the condition number can be found by the cond method in the numpy module"""
from numpy.linalg import \
             cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [18]:
#solving of linear equation 
#decompostion of the a matrix int lu 
import numpy as np

u = np.array([[4, 3, -5], 
              [0, -2.5, 2.5], 
              [0, 0, 12]])
l = np.array([[1, 0, 0], 
              [-0.5, 1, 0], 
              [2, -0.8, 1]])

print('LU=', np.dot(l, u))


LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [21]:
#gauss-seidel method of sloving linear equations
#first we check if the matrix if diagonally dominant or not 
a= [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

# Find diagonal coefficients
diag = np.diag(np.abs(a)) 

# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag 

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')

matrix is diagonally dominant


In [22]:
#since the matrix is guaranteed to converge we can use 
#Guass-seidel method to solve it
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(-5)
    x = np.array([x1, x2, x3])
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

Iteration results
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, 1.5875
2, 2.7437, -0.3188, 2.9275
3, 2.9673, 0.4629, 3.8433
4, 3.0177, 1.0226, 4.4332
5, 3.0290, 1.3885, 4.8059
6, 3.0315, 1.6208, 5.0397
7, 3.0321, 1.7668, 5.1861
8, 3.0322, 1.8582, 5.2776
9, 3.0322, 1.9154, 5.3348
10, 3.0323, 1.9512, 5.3705
11, 3.0323, 1.9735, 5.3929
12, 3.0323, 1.9875, 5.4068
13, 3.0323, 1.9962, 5.4156
14, 3.0323, 2.0017, 5.4210
Converged!


In [26]:
#solving systems of linear equations in python through numpy function 
#the code below is using the lu decomposition to get the results
import numpy as np
A=np.array([[4,3,-5],[-2,-4,5],[8,8,0]])
print(A)
Y=np.array([2,5,-3])
print(Y)
x=np.linalg.solve(A,Y)
print(x)

3
[[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
[ 2  5 -3]
[ 2.20833333 -2.58333333 -0.18333333]


In [30]:
#solving the problem form the privouse cell with matrix inverse 
#approach

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, Y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [39]:
from scipy.linalg import lu
P,L,U=lu(A)
print("p:\n",P)
print("L:\n",L)
print("U:\n",U)
print("LU:\n",np.dot(L,U))


p:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
[[24.]
 [-5.]
 [ 5.]]
